### ISSUE TITLE
SendTextMessage?!

### ISSUE THREAD

**Issue by Apollon77** [soef/alexa-remote#1]
What can this function do? Can I send text commands to alexa as I would speak to her?
Can you bring that in the adapter too please? :-)
Then we could do a "sayit" integration ... (in theory)

**Comment by soef** [comment]
SendMessage oder SendCommand is already in the ioBroker-Adapter. The commands are in the Commands section under each of the Echo devices. e.g. forward, next, pause, play, volume...
